resolver: lts-10.5
packages:
- '.'
extra-deps: []
extra-package-dbs: []
allow-newer: true
allow-different-user: true
install-ghc: true
system-ghc: false
apply-ghc-options: everything
ghc-options:
build:
  prefetch: true
compiler: ghc-8.2.2
compiler-check: match-exact
